In [1]:
import numpy as np

In [3]:
v = np.array([[1,2,3,4], [1,1,1,1],[1,1,2,3]])
v

array([[1, 2, 3, 4],
       [1, 1, 1, 1],
       [1, 1, 2, 3]])

In [6]:
v.sum(axis=0)

array([3, 4, 6, 8])

In [8]:
v.sum(axis=1)

array([10,  4,  7])

In [17]:
v[::-1]

array([[1, 1, 2, 3],
       [1, 1, 1, 1],
       [1, 2, 3, 4]])

In [19]:
v.cumsum(axis=0)

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 6, 8]], dtype=int32)

In [21]:
v.cumsum(axis=1)

array([[ 1,  3,  6, 10],
       [ 1,  2,  3,  4],
       [ 1,  2,  4,  7]], dtype=int32)

In [23]:
np.mean(v, axis=0)

array([1.        , 1.33333333, 2.        , 2.66666667])

In [25]:
np.mean(v, axis=1)

array([2.5 , 1.  , 1.75])

In [29]:
np.expand_dims(v, axis=1)

array([[[1, 2, 3, 4]],

       [[1, 1, 1, 1]],

       [[1, 1, 2, 3]]])